export const HOME = "/"
export const VIEWPETS = "/viewpets"
export const VIEWAPPOINTMENTS = "/viewappointments"
export const REGISTPET = "/registpet"
export const EDITPET = "/editpet"
export const CREATEAPPOINTMENT = "/createappointment"
export const NOTFOUND = "/*"
